name: blurhash
description: combination of  flutter_blurhash and blurhash-dart to create a full
  flutter implementation of the blurha.sh algorithm.

version: 0.1.1

publish_to: "none"

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  string_validator: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
